---
# This playbook will install mysql and create db user and give permissions.
- name: Set MySQL root
  debconf:
   name: mysql-server
   question: mysql-server/root_password
   value: "{{ mysql_root_password }}"
   vtype: password

- name: Set MySQL root again
  debconf:
   name: mysql-server
   question: mysql-server/root_password_again
   value: "{{ mysql_root_password }}"
   vtype: password

- name: Install Mysql package
  apt: name={{ item }} state=installed
  with_items:
   - mysql-server
   - python-mysqldb

- name: Select default mysql directory
  command: usermod -d /var/lib/mysql/ mysql

- name: Create Mysql configuration file
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: 0644
    backup: yes

#Problemas iniciando servicio con modulo service (no lo inicia)
- name: Started Mysql service
  command: service mysql start
  register: start

- name: Started output
  debug: var=start

- name: Enabled Mysql Service
  service: name=mysql state=started enabled=yes

- name: Create Application Database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ dbname }}"
    state: present


- name: Create Application DB User
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ dbuser }}"
    password: "{{ upassword }}"
    priv: "*.*:ALL"
    host: '%'
    state: present
