---
# These tasks install http and the php modules.

- name: Install apache2 and php etc
  apt: name={{ item }} state=present
  with_items:
   - apache2
   - php7.0
   - php7.0-mysql
   - libapache2-mod-php7.0
   - git

- name: apache2 service state
  service: name=apache2 state=started enabled=yes
